### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by gingin-s** [gingin-s/furima-37445#20]
### フリマアプリのURL
https://furima-37445.herokuapp.com/
### Basic認証のIDとパスワード
- ID : gin2  
- password : ag23
### 出品者用のメールアドレスとパスワード
- email : tanaka@gmail.com
- password : aaa123
### 購入者用のメールアドレスとパスワード
- email : yamada@gmail.com
- password : aaa123

**Comment by snkw-works** [comment]
@gingin-s さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されるよう修正しましょう**
「やや傷"や汚れ"あり」「傷や汚れ"あり"」が正しく表示されていない状態です。
<img width="335" alt="スクリーンショット_2022-02-22_9_32_33" src="https://user-images.githubusercontent.com/54050089/155042456-8f1c9cc0-f6cf-4a3a-8d7c-f9cc64f7bc45.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@gingin-s さん、フリマアプリ達成要件分の開発お疲れ様でした！
修正が確認でき、正常に動作することが確認できました！ **LGTM** です！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/155047104-74ec2ac6-c467-4c37-a94d-520986c1e882.png)

**Comment by gingin-s** [comment]
ありがとうございました！
